### ISSUE TITLE
Today's update breaks the extension

### ISSUE THREAD

**Issue by chdslv** [fthx/hide-panel#10]
Today's update breaks the extension, so went back to the older version, older extension.js, which works with Gnome shell 40.2 with Arch

**Comment by fthx** [comment]
Hum, today I did only change metadata!
So, I look at this now.

Thanks for BR.

**Comment by fthx** [comment]
I don't have any issue running my Fedora 34 VM.
What are the errors in logs (search "fthx" in All tab)?

**Comment by fthx** [comment]
Feel free to reopen if needed.
I don't have any other BR these days.
