### ISSUE TITLE
Bug: quick tab for app disappears

### ISSUE THREAD

**Issue by BramFran** [fthx/hide-panel#12]
Quick access tab of the current application (see the image below) does not show, after enabling this extension and unhiding the panel. Consequently, the corresponding app menu cannot be opened.

![shell-appmenu-shell](https://user-images.githubusercontent.com/76474360/128315484-b4223e67-d49f-458e-8391-9166afa6c3a7.png)
(image taken from GNOME help app)

**Comment by fthx** [comment]
Thanks for BR.
https://github.com/fthx/hide-panel/commit/6851efba20a15c5d69bb0279b15766ac96d45019
