### ISSUE TITLE
Hide panel when maximised

### ISSUE THREAD

**Issue by Spinnekop** [fthx/hide-panel#2]
Hi. If you could make an option to hide when a window is maximised rather than all the time it would be perfection!

**Comment by fthx** [comment]
Hi,

No I won't do that, that's not the scope of this extension.
I suggest you:
https://extensions.gnome.org/extension/545/hide-top-bar/
that seems to fit your needs.

**Comment by Spinnekop** [comment]
Hide top bar doesn't work for gnome 40....

No worries

**Comment by fthx** [comment]
Well, GS 40 compatibility needs quite some work (cf. BaBar extension)...
