### ISSUE TITLE
Creates issues with 3 finger gesture in Gnome 40

### ISSUE THREAD

**Issue by mattpepin** [fthx/hide-panel#3]
I really like the extension, but it makes it very hard to use the three-finger vertical gesture to show activities. It somehow confuses the logic.

**Comment by fthx** [comment]
Unfortunately I cannot reproduce since I do use Fedora 34 in VM for GS 40 testing. The gestures do not work in VM.
Could you describe precisely (screen recording if needed) the problem here?

**Comment by mattpepin** [comment]
I made a screen recording, but it's pretty large. I uploaded it to dropbox (you might have to download it, it seems the dropbox preview can't keep up):

https://www.dropbox.com/s/8hzwa3w4syhk1ci/Screencast%20from%2004-05-2021%2006%3A11%3A22%20AM.webm?dl=0

I think the problem is that the top bar starts showing as soon as the gesture begins. When it happens, the screen is offset vertically and it probably creates a bug for the algorithm to detect a complete gesture. I have to travel almost the whole touchpad with my fingers to make the gesture work, it's really annoying.

With that said, I think the 3-finger vertical swipe could also be improved in Gnome too. It does not work as well as the 3-finger horizontal swipe.

**Comment by mattpepin** [comment]
I think it would make the animation smoother, even when using the top corner, if the bar was shown only at the end of the animation.

**Comment by fthx** [comment]
Lines 36-37 you can try to change 'showing' and 'hiding' with 'shown' and 'hidden'.
I tried that first when I made this extension. But that causes the dock to be shifted and imho that's not good. It should be done in another way I don't know. That's my opinion for GS **3.36-38**

But try it in GS 40 and tell me if it sounds better for you.
