### ISSUE TITLE
Menus pop up when clicking on the top of the screen

### ISSUE THREAD

**Issue by emirror-de** [fthx/hide-panel#5]
Hi there,
thanks for this nice extension!

I am asking myself if the following behavior is intended?
- Move the mouse pointer to the top of the screen (for example in the horizontal center)
- Click
- The notification panel is shown.
When moving along to the right or left, the same behavior is noticed, e.g. for the Activities button or the menu on the right. Also applies to the tray icons that are shown by KStatusNotifierItem/AppIndicator Support extension.

Is this intended like that, or is this a bug? I am on Gnome 3.38.4

Best regards, Lewin

**Comment by fthx** [comment]
That's intended. I need this 1px line to not remove the hot corner. The extension would be much less tiny if I had to recreate the hot corner instance.
With time, I find it useful since I can blindly access these menus without entering overview...
