### ISSUE TITLE
Stopped working after an update

### ISSUE THREAD

**Issue by chdslv** [fthx/hide-panel#8]
Stopped working after an update to version 5.
![error](https://user-images.githubusercontent.com/28350701/117878056-9f7c3f00-b2a5-11eb-92b2-b486c3e741e1.png)
version 3 works. Version 4 and 5 doesn't.

**Comment by fthx** [comment]
Sorry for that. A quick change at work to satisfy review and I did not test it.
https://github.com/fthx/hide-panel/commit/095db8ff8fad55efd51c888527b3bde393f9521d

**Comment by chdslv** [comment]
Version 6 is working, thanks!
